//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExpenseView
    {
        public string CategoryName { get; set; }
        public int UserID { get; set; }
        public int CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int CategoryID { get; set; }
    }
}
