//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Reports = new HashSet<Report>();
            this.ApproverUsers = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public int ApproverID { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<User> ApproverUsers { get; set; }
        public virtual User UserApprover { get; set; }
    }
}
